services:
  bridge:
    image: ghcr.io/jmgstudios/discordstoatbridgebot:latest
    container_name: stoat-discord-bridge
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ~/.config/bridgebot/.env:/app/.env
      - ~/.config/bridgebot/notified_users.json:/app/notified_users.json
